# inventory.yaml
meta:
  version: 1
  generated_at: "2025-12-11T19:27:00Z"
devices:
  - hostname: HOM-SWA-002
    mgmt_ip: 10.0.999.5
    site: lab
    role: access
    vendor: cisco
    os_type: cisco_ios
    os_version: 17.2.7
  - hostname: HOM-SWA-001
    mgmt_ip: 10.0.98.5
    site: lab
    role: access
    vendor: cisco
    os_type: cisco_ios
    os_version: 17.2.7
